name: Test de Motores SmartDash
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verificar_cuenta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: Saludo del Sistema
        run: |
          echo "ðŸš€ Iniciando SmartDash en cuenta almasana..."
          echo "âœ… Entorno Linux listo."
          echo "âœ… GitHub Actions desbloqueado."

      - name: Verificar Python
        run: python --version
